
name: fetch-updates
on:
  schedule:
    - cron: '0 4 * * *'  # daily 09:30 IST
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml feedparser
      - name: Fetch updates
        run: |
          python scripts/fetch_updates.py
      - name: Commit & push
        run: |
          git config user.name "actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/amendments.json
          git commit -m "chore: refresh amendments.json [skip ci]" || echo "No changes"
          git push
