name: Fetch amendments daily
on:
  schedule:
    - cron: '30 1 * * *'  # ~07:00 IST
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml python-dateutil
      - name: Fetch amendments
        env:
          MAX_ITEMS: '60'
        run: |
          python scripts/fetch_amendments.py
      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/amendments.json
            git commit -m "chore: auto-update amendments.json"
            git push
          else
            echo 'No changes'
